gfx906/MI50/MI60/Vega VII rocBLAS fix
DTensile_CODE_OBJECT_VERSION=V5 caused the
pytorch benchmark on gfx906 to fail on error:

:0:rocm_sdk_builder_gfx906/src_projects/clr/hipamd/src/hip_global.cpp:114 : 113508223548 us: [pid:7768  tid:0x7f19583a7040] Cannot find Symbol with name: Cijk_Alik_Bljk_SB_MT32x32x16_SE_APM1_AF0EM1_AF1EM1_AMAS0_ASAE01_ASCE01_ASEM1_BL1_BS1_DTLA0_DTLB0_EPS0_FL1_GLVWA4_GLVWB4_GRVW4_GSU1_GSUASB_ISA906_IU1_K1_KLA_LPA1_LPB1_LDL1_LRVW1_MDA2_MMFGLC_NLCA1_NLCB1_ONLL1_PK0_PGR0_PLR1_SIA1_SU32_SUM0_SUS256_SVW4_SNLL0_TT2_4_USFGRO1_VAW1_VS1_VW1_VWB1_WG16_8_1_WGM8

fixes: https://github.com/lamikr/rocm_sdk_builder/issues/180

Signed-off-by: Mika Laitio <lamikr@pilppa.org>