AMDMiGraphX Fedora 40 build error fix
Enable code for exception_ptr only if it is used.
Not sure whether this error was caused by optimizion
as patch was not needed on Fedora 39, Ubuntu 23.10 or on Mageia 9.

Error message was:
AMDMIGraphX/src/include/migraphx/par.hpp:58:22: error: no member named 'exception_ptr' in namespace 'std'

Fixes: https://github.com/lamikr/rocm_sdk_builder/issues/12

Signed-off-by: Mika Laitio <lamikr@gmail.com>