add clang 18 triton build fix
disable error caused by the deprecation warning that occurs
on some linux distros

Triton/lib/Analysis/Allocation.cpp
In file included from /home/lamikr/own/rocm/src/sdk/rocm_sdk_builder_633/src_projects/triton/lib/Analysis/Allocation.cpp:1:
In file included from /home/lamikr/own/rocm/src/sdk/rocm_sdk_builder_633/src_projects/triton/include/triton/Analysis/Allocation.h:4:
In file included from /home/lamikr/own/rocm/src/sdk/rocm_sdk_builder_633/src_projects/triton/include/triton/Analysis/Utility.h:4:
In file included from /home/lamikr/.triton/llvm/llvm-2619c2ed-ubuntu-x64/include/mlir/Analysis/DataFlowFramework.h:19:
In file included from /home/lamikr/.triton/llvm/llvm-2619c2ed-ubuntu-x64/include/mlir/IR/Operation.h:16:
In file included from /home/lamikr/.triton/llvm/llvm-2619c2ed-ubuntu-x64/include/mlir/IR/Block.h:16:
In file included from /home/lamikr/.triton/llvm/llvm-2619c2ed-ubuntu-x64/include/mlir/IR/BlockSupport.h:16:
In file included from /home/lamikr/.triton/llvm/llvm-2619c2ed-ubuntu-x64/include/mlir/IR/Value.h:16:
In file included from /home/lamikr/.triton/llvm/llvm-2619c2ed-ubuntu-x64/include/mlir/IR/Types.h:12:
In file included from /home/lamikr/.triton/llvm/llvm-2619c2ed-ubuntu-x64/include/mlir/IR/TypeSupport.h:16:
In file included from /home/lamikr/.triton/llvm/llvm-2619c2ed-ubuntu-x64/include/mlir/IR/MLIRContext.h:12:
In file included from /home/lamikr/.triton/llvm/llvm-2619c2ed-ubuntu-x64/include/mlir/Support/LLVM.h:23:
In file included from /home/lamikr/.triton/llvm/llvm-2619c2ed-ubuntu-x64/include/llvm/Support/Casting.h:20:
In file included from /usr/lib/gcc/x86_64-mageia-linux/12/../../../../include/c++/12/memory:66:
/usr/lib/gcc/x86_64-mageia-linux/12/../../../../include/c++/12/bits/stl_tempbuf.h:263:8: error: 'get_temporary_buffer<mlir::Allocation::BufferT *>' is deprecated [-Werror,-Wdeprecated-declarations]
  263 |                 std::get_temporary_buffer<value_type>(_M_original_len));

Signed-off-by: Mika Laitio <lamikr@pilppa.org>