hipTensor use clang instead of hipcc
- fixes on mageia a following error:
  undefined reference to llvm::DisableABIBreakingChecks

Signed-off-by: Mika Laitio <lamikr@gmail.com>